name: symfony8-eval
volumes:
  db_data: {}
services:
  db: 
    image: mariadb:11.8.5
    container_name: symfony8-eval-db
    restart: unless-stopped
    ports: ["3308:3306"]
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db_eval
      MYSQL_USER: eval
      MYSQL_PASSWORD: eval2503
  web: 
    # image: php:8.4-apache
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: symfony8-eval-web
    restart: unless-stopped
    ports: ["9005:80"]
    depends_on: ['db']
    links: ['db']
    volumes:
      - ./app:/var/www/html

