api_platform:
    title: Bienvenue dans l'API Platform
    version: 1.0.0
    formats:
        json: ['application/json']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
